### ISSUE TITLE
menu 모듈 에러

### ISSUE THREAD

**Issue by takearest118** [wacilpong/yolo#1]
## 재현순서
터미널에서 아래와 같이 실행
> $ git clone git@github.com:wacilpong/yolo.git
> $ cd yolo
> $ npm install
> $ ng serve --host 0.0.0.0 --port 4300

## 현상
menu 모듈을 찾을 수 없다는 메세지가 콘솔에 출력됨
아래 스크린샷 참고

### 스크린샷
![2017-12-22 4 07 51](https://user-images.githubusercontent.com/2114960/34288744-5e2d4dba-e732-11e7-857a-f9660b42a6bc.png)

**Comment by takearest118** [comment]
@wacilpong 혹시 윈도우에서 작업하는 건가요?

**Comment by wacilpong** [comment]
@takearest118 네 윈도우에서 작업하고 있습니다...! 늦게 봐서 죄송해요

**Comment by takearest118** [comment]
@wacilpong 잘되네요
