### ISSUE TITLE
[논의] 영상리스트 레이아웃

### ISSUE THREAD

**Issue by wacilpong** [wacilpong/yolo#3]
## 논의
디자인에서는 리스트의 영상부분이 회색처리되어 있는데요. 

작업을 하다보니 해당 레이아웃에 맞춰서 바로 youtube-player를 삽입해야 하는지, 혹은 리스트에는 썸네일만 표시해준 후 클릭했을 때 유튜브 url로 들어가도록 해야하는 지 논의가 필요할 것 같습니다.

## 임시처리
![thumb](https://user-images.githubusercontent.com/27843313/34431024-5b48b5b8-ecae-11e7-93da-d4401b745256.png)

일단은 이미지와 같이 썸네일로 표시하고 클릭했을 때 youtube url로 들어가지도록 처리했습니다.  하지만 아무래도 영상을 바로 볼 수 있도록 youtube-player를 코드 내에 삽입하는 것도 좋을 것 같은데 어떻게 할까요?

**Comment by takearest118** [comment]
@wacilpong 디자인팀과 논의후 피드백 드리겠습니다

**Comment by youlim90** [comment]
@wacilpong 안녕하세요 디자이너 김그레입니다~ 유투브 영상을 보여지게하는 어플 특성상 youtube url로 연결 시키는 방법도 좋을것 같습니다. 속도적인 면이나 어플의 특성을 고려했을 때 김그레의 의견입니다 ~ 다른 생각이시면 또 글 남겨주세용 ^^

**Comment by takearest118** [comment]
@wacilpong 저도 동의합니다
리스트 페이지의 페이징에 관한 부분은 디자이너가 심플리에 업데이트 했을때 보시고 진행하시면 됩니다.

**Comment by wacilpong** [comment]
@youlim90 @takearest118 알겠습니다. 그럼 저렇게 진행하겠습니다. 그러면 썸네일에 재생버튼을 달면 어떨까요? 제가 직접 처리해도 되고, 디자인을 해주셔도 좋을 것 같습니다. ^^~

**Comment by takearest118** [comment]
@wacilpong 오늘 TFCD 행사 당일이여서 피드백이 늦어질것 같습니다

**Comment by youlim90** [comment]
@wacilpong youtube 화면이랑 동일하게 해주시면될것 같습니다 ~ (현재 유투브는 마우스 호버됐을때 반투명 화살표 나오게 되어있네요~)
