### ISSUE TITLE
아이폰 실제 기기에서 영상 리스트 비표시

### ISSUE THREAD

**Issue by takearest118** [wacilpong/yolo#4]
실제 아이폰7 사파리, 크롬에서 열어보면 영상 리스트들이 표시되지 않는 현상이 발생

**Comment by wacilpong** [comment]
앗 혹시 environment 파일에 API key 입력하셨나요? key가 커밋되면 안될 거라고 생각해서 뺐거든요. README에도 아래와 같이 적어두었습니다!!

```
You need to set the youtube API token and key in `/environments/environment.ts`
```

**Comment by takearest118** [comment]
@wacilpong pc 웹 브라우저에서는 잘 동작해요

**Comment by wacilpong** [comment]
@takearest118 확인했습니다! 원인 파악중입니다.
